<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ModSecurity Reports</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #f4f6f9;
        }
        .card-hover:hover {
            transform: translateY(-2px);
            box-shadow: 0 0.5rem 1rem rgba(0,0,0,.15);
        }
    </style>
</head>

<body>

<nav class="navbar navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">
            🛡 ModSecurity Dashboard
        </span>
    </div>
</nav>

<div class="container">

    <div class="row mb-4">
        <div class="col">
            <h2 class="fw-bold">Security Reports</h2>
            <p class="text-muted">
                View and analyze ModSecurity audit events and error reports.
            </p>
        </div>
    </div>

    <div class="row g-4">

        <!-- Nginx Errors -->
        <div class="col-md-6 col-lg-4">
            <div class="card card-hover h-100">
                <div class="card-body">
                    <h5 class="card-title">Nginx ModSecurity Errors</h5>
                    <p class="card-text text-muted">
                        View ModSecurity error logs generated by Nginx.
                    </p>
                </div>
                <div class="card-footer bg-transparent border-top-0 text-end">
                    <a href="nginx_logs_report.php" class="btn btn-primary">
                        View Nginx Errors →
                    </a>
                </div>
            </div>
        </div>

        <!-- Audit Logs -->
        <div class="col-md-6 col-lg-4">
            <div class="card card-hover h-100">
                <div class="card-body">
                    <h5 class="card-title">ModSecurity Audit Logs</h5>
                    <p class="card-text text-muted">
                        Detailed request audit entries and triggered rules.
                    </p>
                </div>
                <div class="card-footer bg-transparent border-top-0 text-end">
                    <a href="modsec_audit_logs_report.php" class="btn btn-primary">
                        View Audit Log →
                    </a>
                </div>
            </div>
        </div>


        <!-- Audit Grouping -->
        <div class="col-md-6 col-lg-4">
            <div class="card card-hover h-100">
                <div class="card-body">
                    <h5 class="card-title">ModSecurity Audit Grouping Report</h5>
                    <p class="card-text text-muted">
                        Audit logs grouped by IP, Rule ID, etc
                    </p>
                </div>
                <div class="card-footer bg-transparent border-top-0 text-end">
                    <a href="modsec_audit_grouping_report.php" class="btn btn-primary">
                        View Audit Report →
                    </a>
                </div>
            </div>
        </div>

    </div>

</div>

<footer class="text-center text-muted py-4 mt-5">
    <small>ModSecurity Dashboard v2.0</small>
</footer>

</body>
</html>
